config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
  end

  def show
  end

  def edit
  end

  def update
    @article = Article.update(article_params)
  end

  def destroy
    @article.destroy
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class= "mx-3" >
  <%= simple_form_for(article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <div class= "btn btn-primary"><%= f.submit %></div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>
<br>
<div class= "mx-3 btn btn-success">
<%= link_to "Back to the Articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class= "mx-3">
<ul>
  <% @articles.each do |article| %>
  <li class= "py-3"><%= link_to article.title, article_path(article) %> - <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>
<br>
<%= link_to "Create a new Article", new_article_path %>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article %>
<br>
<div class= "mx-3 btn btn-success">
<%= link_to "Back to the Articles", articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>